#!/usr/bin/env bash
# Vendors the design pipeline's leaf skills from their upstream repos.
# Idempotent: run again to update. Writes provenance (repo + commit) to VENDOR.md.
#
#   bash .claude/skills/design/vendor.sh
#
# Every leaf is MIT-licensed; each vendored folder keeps its upstream LICENSE.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"   # .claude/
SKILLS="$ROOT/skills"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

# name <TAB> repo <TAB> path-in-repo <TAB> license-path-in-repo
MANIFEST=$(cat <<'EOF'
better-ui	jakubkrehel/skills	skills/better-ui	LICENSE
better-typography	jakubkrehel/skills	skills/better-typography	LICENSE
better-colors	jakubkrehel/skills	skills/better-colors	LICENSE
better-layout	jakubkrehel/skills	skills/better-layout	LICENSE
better-writing	jakubkrehel/skills	skills/better-writing	LICENSE
better-accessibility	jakubkrehel/skills	skills/better-accessibility	LICENSE
better-interface	jakubkrehel/skills	skills/better-interface	LICENSE
ui-design	mblode/agent-skills	skills/ui-design	LICENSE.md
ui-animation	mblode/agent-skills	skills/ui-animation	LICENSE.md
product-design	mblode/agent-skills	skills/product-design	LICENSE.md
emil-design-eng	cal1888/claude-code-skills	skills/emil-design-eng	LICENSE
frontend-design	anthropics/skills	skills/frontend-design	skills/frontend-design/LICENSE.txt
design-review	humbleteam/design-review	.	LICENSE
ux-audit	EliaAlberti/ux-audit-skill	.	LICENSE
ux-flow-planner	richhemsley3/claude-design-skills	skills/ux-flow-planner	LICENSE
information-architect	richhemsley3/claude-design-skills	skills/information-architect	LICENSE
EOF
)

clone() { # $1=repo -> echoes local checkout dir
  local repo="$1" dir="$TMP/$(echo "$repo" | tr '/' '_')"
  [ -d "$dir" ] || git clone --depth 1 -q "https://github.com/$repo.git" "$dir"
  echo "$dir"
}

PROV=""
while IFS=$'\t' read -r name repo path lic; do
  [ -n "$name" ] || continue
  src="$(clone "$repo")"
  [ -d "$src/$path" ] || { echo "MISSING upstream: $repo/$path" >&2; exit 1; }

  rm -rf "${SKILLS:?}/$name"
  mkdir -p "$SKILLS/$name"
  # evaluations/ is upstream regression fixtures, never loaded during a task
  (cd "$src/$path" && tar -c --exclude=.git --exclude=evaluations .) | tar -x -C "$SKILLS/$name"
  if [ -f "$src/$lic" ]; then
    cp "$src/$lic" "$SKILLS/$name/LICENSE"
  else
    echo "  !! no licence at $repo/$lic for $name -- fix the manifest" >&2; exit 1
  fi

  sha="$(git -C "$src" rev-parse --short HEAD)"
  PROV="$PROV| \`$name\` | [$repo](https://github.com/$repo) | \`$path\` | \`$sha\` | MIT |"$'\n'
  echo "  vendored $name  <- $repo/$path @ $sha"
done <<< "$MANIFEST"

cat > "$SKILLS/design/VENDOR.md" <<EOF
# Vendored leaf skills

Generated by \`vendor.sh\` on $(date -u +%Y-%m-%d). Do not hand-edit the vendored
folders — \`vendor.sh\` wipes and re-copies them. Re-run it to update:

\`\`\`bash
bash .claude/skills/design/vendor.sh
\`\`\`

| Skill | Upstream | Path | Commit | License |
| --- | --- | --- | --- | --- |
$PROV
Each folder keeps its upstream \`LICENSE\`. All MIT.
\`evaluations/\` directories are excluded — upstream regression fixtures that never load during a task.
EOF
echo "wrote $SKILLS/design/VENDOR.md"

# opencode reads .claude/skills natively but keeps agents under .opencode.
# Both spellings ship in the wild, so link both.
PROJ="$(dirname "$ROOT")"
mkdir -p "$PROJ/.opencode"
ln -sfn ../.claude/agents "$PROJ/.opencode/agents"
ln -sfn ../.claude/agents "$PROJ/.opencode/agent"
echo "linked .opencode/agents -> .claude/agents"
